@URL=http://localhost:3000

### Get health status
GET {{URL}}/health HTTP/1.1
Content-Type: application/json

### Create a new short URL
POST {{URL}}/create HTTP/1.1
Content-Type: application/json

{
  "url": "https://www.google.com",
  "password": "1234",
  "expiresAt": "2024-10-02"
}

### Redirect to the original URL
GET {{URL}}/l/JNu95?password=1234 HTTP/1.1
Content-Type: application/json

### Invalid to link
PUT {{URL}}/l/JNu95?password=1234 HTTP/1.1
Content-Type: application/json

### Get the stats of a short URL
GET {{URL}}/l/3zt8I/stats HTTP/1.1
Content-Type: application/json